export const PHASE_ONE_PUBLISH_BLOCK_MESSAGE =
  'Publishing is disabled in phase one. Create drafts only.'

export const SUPPORTED_APP_SLUGS = [
  'driver',
  'rider',
  'supervisor',
  'operator-dashboard',
  'enterprise-dashboard',
] as const

export const SUPPORTED_PAGE_KEYS = [
  'homepage',
  'solutions',
  'solutionsEnterprisesPassengers',
  'solutionsOperatorsDrivers',
  'apps',
  'appDetail',
  'navigation',
] as const

export type SupportedPageKey = (typeof SUPPORTED_PAGE_KEYS)[number]
export type SupportedAppSlug = (typeof SUPPORTED_APP_SLUGS)[number]

export type QueryInspectionDefinition = {
  pageKey: SupportedPageKey
  route: string
  documentType: string
  queryName: string
  sourceFiles: string[]
  singleton: boolean
  slugRequired?: boolean
  supportedSlugs?: readonly string[]
  defaultDocumentId: string
  seoFields: string[]
  fields: string[]
}

export const QUERY_INSPECTION_MAP: Record<SupportedPageKey, QueryInspectionDefinition> = {
  homepage: {
    pageKey: 'homepage',
    route: '/[locale]',
    documentType: 'homePage',
    queryName: 'homePageQuery',
    sourceFiles: ['src/lib/sanity/queries.ts', 'src/app/[locale]/(main)/page.tsx'],
    singleton: true,
    defaultDocumentId: 'homePage',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'hero.title',
      'hero.titleHighlight',
      'hero.subtitle',
      'hero.primaryCta.text',
      'hero.primaryCta.href',
      'hero.secondaryCta.text',
      'hero.secondaryCta.href',
      'overview.heading',
      'overview.subtitle',
      'overview.features[].title',
      'overview.features[].description',
      'featureTabs.heading',
      'featureTabs.subtitle',
      'featureTabs.tabs[].label',
      'featureTabs.tabs[].title',
      'featureTabs.tabs[].description',
      'featureTabs.tabs[].features[].text',
      'screenshotCarousel.heading',
      'screenshotCarousel.subtitle',
      'screenshotCarousel.items[].title',
      'screenshotCarousel.items[].description',
      'screenshotCarousel.items[].category',
      'logoBar.heading',
      'logoBar.subtitle',
      'testimonials.heading',
      'testimonials.subtitle',
      'testimonials.items[].quote',
      'testimonials.items[].author',
      'testimonials.items[].role',
      'testimonials.items[].company',
      'cta.heading',
      'cta.subtitle',
      'cta.primaryCta.text',
      'cta.primaryCta.href',
      'cta.secondaryCta.text',
      'cta.secondaryCta.href',
    ],
  },
  solutions: {
    pageKey: 'solutions',
    route: '/[locale]/solutions',
    documentType: 'solutionsPage',
    queryName: 'solutionsPageQuery',
    sourceFiles: ['src/lib/sanity/queries.ts', 'src/app/[locale]/(main)/solutions/page.tsx'],
    singleton: true,
    defaultDocumentId: 'solutionsPage',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'hero.title.smart',
      'hero.title.mobility',
      'hero.title.practicalResults',
      'hero.subtitle',
      'hero.cta',
      'hero.nodes.operator',
      'hero.nodes.enterprise',
      'hero.nodes.supervisor',
      'hero.nodes.driver',
      'hero.nodes.rider',
      'intro.text',
      'intro.howWeHelp.title',
      'intro.howWeHelp.benefits[]',
      'audienceCards.operators.headline',
      'audienceCards.operators.description',
      'audienceCards.operators.benefits[]',
      'audienceCards.operators.cta',
      'audienceCards.enterprises.headline',
      'audienceCards.enterprises.description',
      'audienceCards.enterprises.benefits[]',
      'audienceCards.enterprises.cta',
      'technology.title',
      'technology.highlights[].text',
      'whyTranzkit.title',
      'whyTranzkit.reasons[]',
      'cta.title',
      'cta.subtitle',
    ],
  },
  solutionsEnterprisesPassengers: {
    pageKey: 'solutionsEnterprisesPassengers',
    route: '/[locale]/solutions/enterprises-passengers',
    documentType: 'solutionsEnterprisesPassengersPage',
    queryName: 'solutionsEnterprisesPassengersPageQuery',
    sourceFiles: [
      'src/lib/sanity/queries.ts',
      'src/app/[locale]/(main)/solutions/enterprises-passengers/page.tsx',
    ],
    singleton: true,
    defaultDocumentId: 'solutionsEnterprisesPassengersPage',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'hero.title',
      'hero.subtitle',
      'hero.cta',
      'audienceSwitcher.tabs.enterprise',
      'audienceSwitcher.tabs.passenger',
      'audienceSwitcher.enterprise.title',
      'audienceSwitcher.enterprise.description',
      'audienceSwitcher.enterprise.features[].title',
      'audienceSwitcher.enterprise.features[].description',
      'audienceSwitcher.passenger.title',
      'audienceSwitcher.passenger.description',
      'audienceSwitcher.passenger.features[].title',
      'audienceSwitcher.passenger.features[].description',
      'overview.text',
      'featureShowcase.title',
      'featureShowcase.subtitle',
      'featureShowcase.features[].title',
      'featureShowcase.features[].description',
      'workflow.enterprise.title',
      'workflow.enterprise.subtitle',
      'workflow.enterprise.steps[].title',
      'workflow.enterprise.steps[].description',
      'workflow.passenger.title',
      'workflow.passenger.subtitle',
      'workflow.passenger.steps[].title',
      'workflow.passenger.steps[].description',
      'appScreens.title',
      'appScreens.subtitle',
      'appScreens.screenshots[].title',
      'appScreens.screenshots[].description',
      'features.overview',
      'features.title',
      'features.items[].title',
      'features.items[].description',
      'features.items[].points[]',
      'testimonials.title',
      'testimonials.subtitle',
      'testimonials.items[].content',
      'testimonials.items[].role',
      'aiImpact.title',
      'aiImpact.subtitle',
      'aiImpact.impactTitle',
      'aiImpact.metrics[].value',
      'aiImpact.metrics[].label',
      'aiImpact.metrics[].description',
      'cta.heading',
      'cta.subtitle',
      'cta.primaryCta.text',
      'cta.primaryCta.href',
      'cta.secondaryCta.text',
      'cta.secondaryCta.href',
    ],
  },
  apps: {
    pageKey: 'apps',
    route: '/[locale]/apps',
    documentType: 'appsPage',
    queryName: 'appsPageQuery',
    sourceFiles: ['src/lib/sanity/queries.ts', 'src/app/[locale]/(main)/apps/page.tsx'],
    singleton: true,
    defaultDocumentId: 'appsPage',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'hero.titlePart1',
      'hero.titlePart2',
      'hero.titlePart3',
      'hero.subtitle',
      'showcase.title',
      'showcase.subtitle',
      'showcase.operatorsSegment.title',
      'showcase.operatorsSegment.description',
      'showcase.operatorsSegment.tabLabel',
      'showcase.enterpriseSegment.title',
      'showcase.enterpriseSegment.description',
      'showcase.enterpriseSegment.tabLabel',
      'showcase.operatorApps[]->slug.current',
      'showcase.enterpriseApps[]->slug.current',
      'cta.heading',
      'cta.subtitle',
      'cta.primaryCta.text',
      'cta.primaryCta.href',
      'cta.secondaryCta.text',
      'cta.secondaryCta.href',
    ],
  },
  solutionsOperatorsDrivers: {
    pageKey: 'solutionsOperatorsDrivers',
    route: '/[locale]/solutions/operators-drivers',
    documentType: 'solutionsOperatorsDriversPage',
    queryName: 'solutionsOperatorsDriversPageQuery',
    sourceFiles: [
      'src/lib/sanity/queries.ts',
      'src/app/[locale]/(main)/solutions/operators-drivers/page.tsx',
    ],
    singleton: true,
    defaultDocumentId: 'solutionsOperatorsDriversPage',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'hero.title',
      'hero.subtitle',
      'hero.cta',
      'overview.text',
      'roleSwitcher.tabs.operator',
      'roleSwitcher.tabs.driver',
      'roleSwitcher.operator.title',
      'roleSwitcher.operator.description',
      'roleSwitcher.operator.features[].title',
      'roleSwitcher.operator.features[].description',
      'roleSwitcher.driver.title',
      'roleSwitcher.driver.description',
      'roleSwitcher.driver.features[].title',
      'roleSwitcher.driver.features[].description',
      'timeline.title',
      'timeline.subtitle',
      'timeline.items[].time',
      'timeline.items[].title',
      'timeline.items[].description',
      'dashboards.title',
      'dashboards.subtitle',
      'dashboards.screenshots[].title',
      'dashboards.screenshots[].description',
      'mobileApps.title',
      'mobileApps.subtitle',
      'mobileApps.features[].title',
      'mobileApps.features[].description',
      'mobileApps.features[].badge',
      'features.overview',
      'features.title',
      'features.items[].title',
      'features.items[].description',
      'features.items[].points[]',
      'aiImpact.title',
      'aiImpact.subtitle',
      'aiImpact.impactTitle',
      'aiImpact.metrics[].value',
      'aiImpact.metrics[].label',
      'aiImpact.metrics[].description',
      'faq.title',
      'faq.subtitle',
      'faq.items[].question',
      'faq.items[].answer',
      'cta.heading',
      'cta.subtitle',
      'cta.primaryCta.text',
      'cta.primaryCta.href',
      'cta.secondaryCta.text',
      'cta.secondaryCta.href',
    ],
  },
  appDetail: {
    pageKey: 'appDetail',
    route: '/[locale]/apps/[slug]',
    documentType: 'app',
    queryName: 'appBySlugQuery',
    sourceFiles: [
      'src/lib/sanity/queries.ts',
      'src/app/[locale]/(main)/apps/driver/page.tsx',
      'src/app/[locale]/(main)/apps/rider/page.tsx',
      'src/app/[locale]/(main)/apps/supervisor/page.tsx',
      'src/app/[locale]/(main)/apps/operator-dashboard/page.tsx',
      'src/app/[locale]/(main)/apps/enterprise-dashboard/page.tsx',
    ],
    singleton: false,
    slugRequired: true,
    supportedSlugs: SUPPORTED_APP_SLUGS,
    defaultDocumentId: 'app',
    seoFields: ['seo.metaTitle', 'seo.metaDescription', 'seo.ogImage', 'seo.keywords'],
    fields: [
      'name',
      'slug.current',
      'tagline',
      'description',
      'category',
      'layoutType',
      'benefits[]',
      'features[].title',
      'features[].description',
      'steps[].title',
      'steps[].description',
      'platforms[]',
      'storeUrls.appStore',
      'storeUrls.googlePlay',
      'cta.heading',
      'cta.subtitle',
      'cta.primaryCta.text',
      'cta.primaryCta.href',
      'cta.secondaryCta.text',
      'cta.secondaryCta.href',
    ],
  },
  navigation: {
    pageKey: 'navigation',
    route: 'global',
    documentType: 'navigation',
    queryName: 'navigationQuery',
    sourceFiles: ['src/lib/sanity/queries.ts'],
    singleton: true,
    defaultDocumentId: 'navigation',
    seoFields: [],
    fields: [
      'mainNav[].label',
      'mainNav[].href',
      'mainNav[].submenu[].label',
      'mainNav[].submenu[].href',
      'mainNav[].submenu[].description',
      'footerNavColumns[].title',
      'footerNavColumns[].links[].label',
      'footerNavColumns[].links[].href',
      'footerText',
    ],
  },
}

export function isSupportedPageKey(value: string): value is SupportedPageKey {
  return SUPPORTED_PAGE_KEYS.includes(value as SupportedPageKey)
}

export function isSupportedAppSlug(value: string): value is SupportedAppSlug {
  return SUPPORTED_APP_SLUGS.includes(value as SupportedAppSlug)
}

export function getDefaultDocumentId(pageKey: SupportedPageKey, slug?: string) {
  if (pageKey === 'appDetail') {
    return slug ? `app.${slug}` : 'app'
  }

  return QUERY_INSPECTION_MAP[pageKey].defaultDocumentId
}
