const L = (en: string, ar: string) => ({ en, ar })

const seo = (
  metaTitleEn: string,
  metaTitleAr: string,
  metaDescriptionEn: string,
  metaDescriptionAr: string,
  keywordsEn: string[],
  keywordsAr: string[],
  canonicalUrl: string,
) => ({
  metaTitle: L(metaTitleEn, metaTitleAr),
  metaDescription: L(metaDescriptionEn, metaDescriptionAr),
  keywords: {
    en: keywordsEn,
    ar: keywordsAr,
  },
  canonicalUrl,
  noIndex: false,
  noFollow: false,
})

const ctaSection = (
  headingEn: string,
  headingAr: string,
  subtitleEn: string,
  subtitleAr: string,
  primaryTextEn: string,
  primaryTextAr: string,
  primaryHref: string,
  secondaryTextEn: string,
  secondaryTextAr: string,
  secondaryHref: string,
) => ({
  heading: L(headingEn, headingAr),
  subtitle: L(subtitleEn, subtitleAr),
  primaryCta: {
    text: L(primaryTextEn, primaryTextAr),
    href: primaryHref,
    openInNewTab: false,
  },
  secondaryCta: {
    text: L(secondaryTextEn, secondaryTextAr),
    href: secondaryHref,
    openInNewTab: false,
  },
  backgroundStyle: 'gradient',
})

export const siteSettingsData = {
  _id: 'siteSettings',
  _type: 'siteSettings',
  siteTitle: L('Tranzkit | Employee Transportation ERP System', 'ترانزكيت | نظام ERP لنقل الموظفين'),
  siteDescription: L(
    'Tranzkit is an Employee Transportation ERP System for planning, dispatch, execution tracking, supplier governance, billing, and settlement control.',
    'ترانزكيت هو نظام ERP لنقل الموظفين لإدارة التخطيط والتشغيل والتتبع الحي وحوكمة المورّدين والتحكم في الفوترة والتسويات.',
  ),
  contactEmail: 'sales@tranzkit.com',
  contactPhone: '+20 100 000 0000',
  socialLinks: {
    linkedin: 'https://www.linkedin.com/company/codefyhub/',
  },
  defaultSeo: seo(
    'Tranzkit | Employee Transportation ERP System',
    'ترانزكيت | نظام ERP لنقل الموظفين',
    'Run employee transport operations with structured planning, live execution visibility, supplier control, and finance-ready billing workflows.',
    'شغّل عمليات نقل الموظفين بتخطيط منظم ورؤية تنفيذ مباشرة وتحكم بالمورّدين ومسارات فوترة جاهزة للفرق المالية.',
    [
      'employee transportation ERP system',
      'employee transport management software',
      'corporate commute platform',
      'transport desk automation',
      'employee transport billing software',
    ],
    [
      'نظام ERP لنقل الموظفين',
      'برنامج إدارة مواصلات الموظفين',
      'منصة النقل المؤسسي',
      'أتمتة مكتب النقل',
      'نظام فوترة نقل الموظفين',
    ],
    'https://www.tranzkit.com/',
  ),
  announcementBar: {
    enabled: true,
    text: L(
      'New: unified planning, dispatch, and settlement controls for employee transportation teams.',
      'جديد: ضوابط موحّدة للتخطيط والتشغيل والتسويات لفرق نقل الموظفين.',
    ),
    link: '/contact',
    variant: 'info',
  },
  jobApplicationForm: {
    name: L('Full Name', 'الاسم الكامل'),
    email: L('Work Email', 'البريد الإلكتروني للعمل'),
    phone: L('Phone Number', 'رقم الهاتف'),
    resume: L('Resume / CV', 'السيرة الذاتية'),
    coverLetter: L('Cover Letter', 'خطاب التقديم'),
    linkedinUrl: L('LinkedIn Profile URL', 'رابط ملف لينكدإن'),
    portfolioUrl: L('Portfolio URL', 'رابط الأعمال'),
    submit: L('Submit Application', 'إرسال الطلب'),
    submitting: L('Submitting...', 'جاري الإرسال...'),
    captcha: L('I am not a robot', 'أنا لست روبوتًا'),
    successMessage: L('Your application has been submitted successfully.', 'تم إرسال طلبك بنجاح.'),
    errorMessage: L('Failed to submit your application. Please try again.', 'تعذر إرسال الطلب. يرجى المحاولة مرة أخرى.'),
    fileTooBig: L('File size must be less than 5MB.', 'يجب أن يكون حجم الملف أقل من 5 ميجابايت.'),
    invalidFileType: L('Invalid file type. Upload PDF, DOC, or DOCX.', 'نوع الملف غير صالح. ارفع PDF أو DOC أو DOCX.'),
    placeholderName: L('Enter your full name', 'اكتب اسمك الكامل'),
    placeholderEmail: L('you@company.com', 'you@company.com'),
    placeholderPhone: L('Enter your phone number', 'اكتب رقم هاتفك'),
    placeholderCoverLetter: L('Write a short introduction about your experience', 'اكتب مقدمة قصيرة عن خبراتك'),
    placeholderLinkedinUrl: L('https://linkedin.com/in/your-name', 'https://linkedin.com/in/your-name'),
    placeholderPortfolioUrl: L('https://your-portfolio.com', 'https://your-portfolio.com'),
  },
}

export const navigationData = {
  _id: 'navigation',
  _type: 'navigation',
  mainNav: [
    { label: L('Home', 'الرئيسية'), href: '/' },
    {
      label: L('Solutions', 'الحلول'),
      href: '/solutions',
      submenu: [
        {
          label: L('For Operators & Drivers', 'للمشغّلين والسائقين'),
          description: L('Control planning, dispatch, and field execution.', 'تحكم في التخطيط والتشغيل والتنفيذ الميداني.'),
          href: '/solutions/operators-drivers',
          icon: 'Shield',
        },
        {
          label: L('For Enterprises & Passengers', 'للشركات والركاب'),
          description: L('Govern demand, service quality, and cost outcomes.', 'حوكمة الطلب وجودة الخدمة ونتائج التكلفة.'),
          href: '/solutions/enterprises-passengers',
          icon: 'Building2',
        },
      ],
    },
    { label: L('Apps', 'التطبيقات'), href: '/apps' },
    { label: L('Pricing', 'الأسعار'), href: '/pricing' },
    { label: L('Resources', 'الموارد'), href: '/resources' },
    { label: L('About', 'من نحن'), href: '/about' },
    { label: L('Contact', 'تواصل معنا'), href: '/contact' },
  ],
  footerNavColumns: [
    {
      heading: L('Platform', 'المنصة'),
      links: [
        { label: L('Employee Transportation ERP', 'ERP لنقل الموظفين'), href: '/solutions' },
        { label: L('Applications', 'التطبيقات'), href: '/apps' },
        { label: L('Pricing', 'الأسعار'), href: '/pricing' },
      ],
    },
    {
      heading: L('Use Cases', 'حالات الاستخدام'),
      links: [
        { label: L('Operators & Drivers', 'المشغّلون والسائقون'), href: '/solutions/operators-drivers' },
        { label: L('Enterprises & Passengers', 'الشركات والركاب'), href: '/solutions/enterprises-passengers' },
      ],
    },
    {
      heading: L('Company', 'الشركة'),
      links: [
        { label: L('About', 'من نحن'), href: '/about' },
        { label: L('Contact', 'تواصل معنا'), href: '/contact' },
      ],
    },
    {
      heading: L('Resources', 'الموارد'),
      links: [
        { label: L('Blog', 'المدونة'), href: '/resources/blog' },
        { label: L('Case Studies', 'دراسات الحالة'), href: '/resources/case-studies' },
        { label: L('FAQ', 'الأسئلة الشائعة'), href: '/resources/faq' },
      ],
    },
  ],
  footerText: L('© {year} Tranzkit. All rights reserved.', '© {year} ترانزكيت. جميع الحقوق محفوظة.'),
}

export const aboutPageData = {
  _id: 'aboutPage',
  _type: 'aboutPage',
  title: 'About Page',
  seo: seo(
    'About Tranzkit | Product by Codefy Hub',
    'عن ترانزكيت | منتج من Codefy Hub',
    'Learn how Tranzkit, a product by Codefy Hub, is built by a team with over 20 years of real-world expertise across logistics, mobility, transportation, IT, and ERP systems.',
    'تعرّف على ترانزكيت، منتج من Codefy Hub، والذي طوّره فريق يمتلك أكثر من 20 عامًا من الخبرة الواقعية في اللوجستيات والتنقل والنقل وتقنية المعلومات وأنظمة ERP.',
    [
      'Tranzkit by Codefy Hub',
      'employee transportation platform team',
      'logistics and mobility expertise',
      'ERP transport software company',
    ],
    [
      'ترانزكيت من Codefy Hub',
      'فريق منصة نقل الموظفين',
      'خبرة في اللوجستيات والتنقل',
      'شركة برمجيات ERP للنقل',
    ],
    'https://www.tranzkit.com/about',
  ),
  hero: {
    title: L('Built From Real Transport Operations, Not Theory', 'مبني على واقع تشغيل النقل وليس على الافتراضات'),
    subtitle: L(
      'Tranzkit is a product by Codefy Hub. Our team brings over 20 years of hands-on experience in logistics, mobility, transportation operations, information technology, and ERP systems.',
      'ترانزكيت هو منتج من Codefy Hub. يجمع فريقنا أكثر من 20 عامًا من الخبرة العملية في اللوجستيات والتنقل وعمليات النقل وتقنية المعلومات وأنظمة ERP.',
    ),
    stats: {
      enterprises: { value: L('20+ Years', '20+ سنة'), label: L('Domain Experience', 'خبرة مجال متخصصة') },
      drivers: { value: L('Bilingual Product', 'منتج ثنائي اللغة'), label: L('English & Arabic Operations', 'عمليات بالإنجليزية والعربية') },
      trips: { value: L('ERP Depth', 'عمق ERP'), label: L('Operations + Finance + Governance', 'تشغيل + مالية + حوكمة') },
    },
  },
  story: {
    heading: L('Why We Built Tranzkit', 'لماذا بنينا ترانزكيت'),
    subtitle: L(
      'We saw transport teams stuck between operational urgency and financial accountability. Tranzkit closes that gap with one object-centric system.',
      'رأينا فرق النقل عالقة بين ضغط التشغيل ومتطلبات المساءلة المالية. ترانزكيت يسد هذه الفجوة عبر نظام واحد مرتكز على الكيانات.',
    ),
    mission: {
      title: L('Our Mission', 'مهمتنا'),
      text: L(
        'Help transport operators and enterprise buyers run employee transportation with measurable service quality, cost control, and audit-ready workflows.',
        'مساعدة مشغّلي النقل والجهات المشترية في الشركات على تشغيل نقل الموظفين بجودة خدمة قابلة للقياس وضبط تكاليف ومسارات جاهزة للتدقيق.',
      ),
    },
    vision: {
      title: L('Our Vision', 'رؤيتنا'),
      text: L(
        'Set a modern operational standard for employee transportation where planning, execution, and finance stay continuously aligned.',
        'إرساء معيار تشغيلي حديث لنقل الموظفين يضمن اتساق التخطيط والتنفيذ والمالية بشكل مستمر.',
      ),
    },
    values: {
      title: L('Our Values', 'قيمنا'),
      innovation: {
        title: L('Operational Innovation', 'ابتكار تشغيلي'),
        description: L(
          'We design practical systems for route planning, dispatch control, and service governance based on real execution constraints.',
          'نصمم أنظمة عملية لتخطيط المسارات والتحكم التشغيلي وحوكمة الخدمة اعتمادًا على قيود التنفيذ الفعلية.',
        ),
      },
      reliability: {
        title: L('Execution Reliability', 'موثوقية التنفيذ'),
        description: L(
          'We prioritize system trust, data clarity, and role-based accountability across daily transport operations.',
          'نركز على موثوقية النظام ووضوح البيانات والمساءلة حسب الأدوار عبر العمليات اليومية للنقل.',
        ),
      },
      sustainability: {
        title: L('Long-Term Value', 'قيمة مستدامة'),
        description: L(
          'We help teams improve route utilization, control waste, and continuously optimize transport economics.',
          'نساعد الفرق على تحسين استغلال المسارات وضبط الهدر والتحسين المستمر لاقتصاديات النقل.',
        ),
      },
    },
  },
  timeline: {
    heading: L('Journey Highlights', 'محطات رئيسية'),
    subtitle: L('Milestones that shaped Tranzkit into an operations-first employee transportation ERP system.', 'محطات شكّلت ترانزكيت كنظام ERP لنقل الموظفين قائم على أولوية التشغيل.'),
    milestones: [
      {
        _key: 'tm-1',
        year: '2004+',
        title: L('Field Experience Foundation', 'بداية الخبرة الميدانية'),
        description: L('Deep exposure to logistics, mobility, and transportation operations across multiple business models.', 'تعرض عميق لعمليات اللوجستيات والتنقل والنقل عبر نماذج أعمال متعددة.'),
        icon: 'MapPinned',
      },
      {
        _key: 'tm-2',
        year: '2012+',
        title: L('ERP and IT Integration Depth', 'تعمّق في ERP وتكاملات تقنية المعلومات'),
        description: L('Expanding from operations into process control, finance alignment, and enterprise systems integration.', 'الانتقال من التشغيل إلى ضبط العمليات ومواءمة المالية والتكامل مع الأنظمة المؤسسية.'),
        icon: 'Database',
      },
      {
        _key: 'tm-3',
        year: '2024',
        title: L('Tranzkit Product Launch by Codefy Hub', 'إطلاق ترانزكيت كمنتج من Codefy Hub'),
        description: L('Consolidating years of domain work into one product for employee transportation governance.', 'تجميع سنوات من الخبرة المتخصصة في منتج واحد لحوكمة نقل الموظفين.'),
        icon: 'Rocket',
      },
    ],
  },
  team: {
    heading: L('Team Perspective', 'منظور الفريق'),
    subtitle: L('Cross-functional expertise across transport operations, finance process design, and software engineering.', 'خبرة متعددة التخصصات عبر تشغيل النقل وتصميم العمليات المالية وهندسة البرمجيات.'),
    members: [
      {
        _key: 'member-1',
        name: 'Codefy Hub Product Team',
        role: L('Transportation ERP Product Specialists', 'متخصصو منتجات ERP للنقل'),
        bio: L('A multidisciplinary team combining operational transport know-how with enterprise-grade software architecture and delivery.', 'فريق متعدد التخصصات يجمع بين خبرة التشغيل في النقل وبناء البرمجيات المؤسسية والتنفيذ.'),
      },
    ],
  },
  careers: {
    heading: L('Join the Team', 'انضم إلى الفريق'),
    subtitle: L('We hire people who can connect operational realities with product execution quality.', 'نبحث عن أشخاص يربطون بين الواقع التشغيلي وجودة التنفيذ المنتجية.'),
    openings: [],
  },
  cta: ctaSection(
    'Want to See How Tranzkit Fits Your Transport Model?',
    'هل تريد رؤية كيف يتوافق ترانزكيت مع نموذج النقل لديكم؟',
    'Book a guided walkthrough with our team and discuss your routes, operations, and billing workflows.',
    'احجز جولة موجهة مع فريقنا وناقش مساراتكم وعملياتكم ومسارات الفوترة لديكم.',
    'Book a Demo',
    'احجز عرضًا تجريبيًا',
    '/contact',
    'Contact Sales',
    'تواصل مع المبيعات',
    '/contact',
  ),
}

export const contactPageData = {
  _id: 'contactPage',
  _type: 'contactPage',
  title: 'Contact Page',
  seo: seo(
    'Contact Tranzkit | Employee Transportation ERP Experts',
    'تواصل مع ترانزكيت | خبراء ERP لنقل الموظفين',
    'Talk to Tranzkit about employee transportation planning, dispatch operations, supplier control, and billing workflows.',
    'تواصل مع ترانزكيت بخصوص تخطيط نقل الموظفين وعمليات التشغيل وضبط المورّدين ومسارات الفوترة.',
    ['contact employee transportation software', 'book transport ERP demo', 'corporate commute platform contact'],
    ['تواصل نظام نقل الموظفين', 'احجز عرض ERP للنقل', 'تواصل منصة النقل المؤسسي'],
    'https://www.tranzkit.com/contact',
  ),
  hero: {
    title: L('Talk to the Tranzkit Team', 'تواصل مع فريق ترانزكيت'),
    subtitle: L(
      'Share your transport model and we will map the right operational and financial setup for your organization.',
      'شاركنا نموذج النقل لديكم وسنحدد التهيئة التشغيلية والمالية المناسبة لمؤسستكم.',
    ),
    emailLabel: L('Email', 'البريد الإلكتروني'),
    phoneLabel: L('Phone', 'الهاتف'),
    locationLabel: L('Location', 'الموقع'),
    email: 'sales@tranzkit.com',
    phone: '+20 100 000 0000',
    location: L('Cairo, Egypt', 'القاهرة، مصر'),
  },
  form: {
    title: L('Book Your Discovery Call', 'احجز مكالمة اكتشاف'),
    subtitle: L('Tell us about your operations, and we will prepare a focused walkthrough.', 'عرّفنا بعملياتكم لنُعد جولة مركزة على احتياجاتكم.'),
    name: L('Full Name', 'الاسم الكامل'),
    namePlaceholder: L('Enter your full name', 'اكتب اسمك الكامل'),
    email: L('Work Email', 'البريد الإلكتروني للعمل'),
    emailPlaceholder: L('you@company.com', 'you@company.com'),
    company: L('Company', 'الشركة'),
    companyPlaceholder: L('Enter your company name', 'اكتب اسم الشركة'),
    phone: L('Phone Number', 'رقم الهاتف'),
    phonePlaceholder: L('Enter your phone number', 'اكتب رقم الهاتف'),
    userType: L('I am a', 'أنا'),
    userTypePlaceholder: L('Select your role', 'اختر الدور'),
    userTypeEnterprise: L('Enterprise Buyer / Admin', 'جهة مشترية / إدارة شركة'),
    userTypeOperator: L('Transport Operator / Supplier', 'مشغّل نقل / مورّد'),
    message: L('Message', 'الرسالة'),
    messagePlaceholder: L('Describe your transport operations, branch setup, and main challenges.', 'صف عمليات النقل لديكم وهيكل الفروع وأهم التحديات.'),
    notRobot: L('I am not a robot', 'أنا لست روبوتًا'),
    submit: L('Send Request', 'إرسال الطلب'),
    submitting: L('Sending...', 'جاري الإرسال...'),
    successTitle: L('Request Received', 'تم استلام الطلب'),
    successMessage: L('Thanks. Our team will contact you shortly.', 'شكرًا لك. سيتواصل معك فريقنا قريبًا.'),
    successButton: L('Send Another Request', 'إرسال طلب آخر'),
  },
  socialLinks: {
    heading: L('Follow Us', 'تابعنا'),
    subtitle: L('Stay updated on product releases and transport operations insights.', 'تابع تحديثات المنتج ورؤى عمليات النقل.'),
  },
}

export const pricingPageData = {
  _id: 'pricingPage',
  _type: 'pricingPage',
  title: 'Pricing Page',
  seo: seo(
    'Tranzkit Pricing | Employee Transportation ERP Plans',
    'أسعار ترانزكيت | خطط ERP لنقل الموظفين',
    'Compare Tranzkit Professional and Premium pricing with per-user rates for system users, employees, drivers, and white labeling.',
    'قارن بين أسعار باقتي ترانزكيت Professional وPremium مع تسعير لكل مستخدم ولموظف ولسائق وخيار العلامة البيضاء.',
    [
      'employee transportation ERP pricing',
      'corporate commute software pricing',
      'transport management SaaS plans',
    ],
    ['أسعار نظام ERP لنقل الموظفين', 'أسعار برنامج النقل المؤسسي', 'خطط SaaS لإدارة النقل'],
    'https://www.tranzkit.com/pricing',
  ),
  hero: {
    title: L('Pricing Built for Real Employee Transport Operations', 'تسعير مبني على واقع تشغيل نقل الموظفين'),
    subtitle: L(
      'Choose the plan that matches your operational scale, governance needs, and branding requirements.',
      'اختر الخطة التي تتوافق مع حجم التشغيل واحتياجات الحوكمة ومتطلبات الهوية المؤسسية.',
    ),
    highlightNoSetupFees: L('Transparent Monthly Pricing', 'تسعير شهري واضح'),
    highlightCancelAnytime: L('Scales by User Type and Operational Role', 'يتوسع حسب نوع المستخدم والدور التشغيلي'),
    highlightFreeTrial: L('Professional and Premium Tiers Available', 'متاح بباقتي Professional وPremium'),
  },
  pricingCards: {
    heading: L('Plans and Rates', 'الباقات والأسعار'),
    subtitle: L('Exact monthly pricing in EGP based on your active user mix.', 'تسعير شهري دقيق بالجنيه المصري وفق مزيج المستخدمين النشطين لديكم.'),
    period: L('per month', 'شهريًا'),
    contactSales: L('Contact Sales', 'تواصل مع المبيعات'),
    plans: [
      {
        _key: 'plan-professional',
        id: 'professional',
        name: L('Professional Tier', 'باقة Professional'),
        badge: L('Core ERP Operations', 'تشغيل ERP أساسي'),
        price: L('From 25 EGP to 350 EGP / user / month', 'من 25 جنيه إلى 350 جنيه / مستخدم / شهر'),
        description: L(
          'For transport teams that need structured operations, dispatch visibility, and finance core controls.',
          'لفرق النقل التي تحتاج إلى تشغيل منظم ورؤية تشغيلية وتحكم مالي أساسي.',
        ),
        features: [
          { _key: 'pro-f-1', text: L('Employee & rider management', 'إدارة الموظفين والركاب'), included: true },
          { _key: 'pro-f-2', text: L('Route planning, trip scheduling, and dispatch board', 'تخطيط المسارات وجدولة الرحلات ولوحة التشغيل'), included: true },
          { _key: 'pro-f-3', text: L('Driver/vehicle management and shift rostering', 'إدارة السائقين/المركبات وجدولة الورديات'), included: true },
          { _key: 'pro-f-4', text: L('Trip execution tracking with GPS live monitoring', 'تتبع تنفيذ الرحلات مع مراقبة GPS مباشرة'), included: true },
          { _key: 'pro-f-5', text: L('Alerts, incident logging, and service notifications', 'التنبيهات وتسجيل الحوادث وإشعارات الخدمة'), included: true },
          { _key: 'pro-f-6', text: L('Client contracts and multi-client operations', 'عقود العملاء وتشغيل متعدد العملاء'), included: true },
          { _key: 'pro-f-7', text: L('Operational analytics, KPI reporting, and export tools', 'تحليلات تشغيلية وتقارير KPI وأدوات تصدير'), included: true },
          { _key: 'pro-f-8', text: L('Task management and team collaboration', 'إدارة المهام وتعاون الفريق'), included: true },
          { _key: 'pro-f-9', text: L('Role-based access control (Arabic/English UI)', 'صلاحيات مبنية على الأدوار (واجهة عربية/إنجليزية)'), included: true },
          { _key: 'pro-f-10', text: L('Finance core: invoicing, AR/AP, and recurring expenses', 'المالية الأساسية: الفوترة وAR/AP والمصروفات المتكررة'), included: true },
          { _key: 'pro-f-11', text: L('CRM, sales pipeline, and service catalog', 'CRM ومسار المبيعات ودليل الخدمات'), included: true },
          { _key: 'pro-f-12', text: L('Knowledge base + multi-agent assistant with AI insights', 'قاعدة معرفة + مساعد متعدد الوكلاء برؤى ذكاء اصطناعي'), included: true },
          { _key: 'pro-f-13', text: L('Smart documents and custom dashboards', 'مستندات ذكية ولوحات مخصصة'), included: true },
          { _key: 'pro-f-14', text: L('Limited web pages, chat widgets, and AI agents', 'صفحات ويب محدودة ووحدات دردشة ووكلاء ذكاء اصطناعي'), included: true },
          { _key: 'pro-r-1', text: L('System User: 200 EGP per user/month', 'مستخدم النظام: 200 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pro-r-2', text: L('Employee: 30 EGP per user/month', 'الموظف: 30 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pro-r-3', text: L('Driver: 100 EGP per user/month', 'السائق: 100 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pro-r-4', text: L('Driver with GPS: 350 EGP per user/month', 'السائق مع GPS: 350 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pro-r-5', text: L('Dependent: 200 EGP per user/month', 'التابع: 200 جنيه لكل مستخدم/شهر'), included: true },
        ],
        ctaText: L('Choose Professional', 'اختر Professional'),
        ctaHref: '/contact',
        highlighted: false,
      },
      {
        _key: 'plan-premium',
        id: 'premium',
        name: L('Premium Tier', 'باقة Premium'),
        badge: L('Advanced Governance + White Label', 'حوكمة متقدمة + علامة بيضاء'),
        price: L('From 25 EGP to 350 EGP / user / month + White Label 20,000 EGP/month', 'من 25 جنيه إلى 350 جنيه / مستخدم / شهر + العلامة البيضاء 20,000 جنيه/شهر'),
        description: L(
          'For organizations requiring white labeling, multi-entity governance, and advanced optimization support.',
          'للمؤسسات التي تحتاج إلى علامة بيضاء وحوكمة متعددة الكيانات ودعم تحسينات متقدمة.',
        ),
        features: [
          { _key: 'pre-f-1', text: L('Everything in Professional', 'كل ما في Professional'), included: true },
          { _key: 'pre-f-2', text: L('White-labeled web and mobile apps', 'تطبيقات ويب وجوال بعلامة بيضاء'), included: true },
          { _key: 'pre-f-3', text: L('White-labeled supervisor and employee mobile apps', 'تطبيقات المشرف والموظف بعلامة بيضاء'), included: true },
          { _key: 'pre-f-4', text: L('Advanced dispatch workflows with auto-allocation rules', 'مسارات تشغيل متقدمة مع قواعد توزيع تلقائي'), included: true },
          { _key: 'pre-f-5', text: L('SLA and service-level compliance tracking', 'تتبع SLA والالتزام بمستويات الخدمة'), included: true },
          { _key: 'pre-f-6', text: L('Multi-branch and multi-entity operations', 'تشغيل متعدد الفروع ومتعدد الكيانات'), included: true },
          { _key: 'pre-f-7', text: L('Trip-level cost, margin, and profitability analytics', 'تحليلات تكلفة الرحلة والهامش والربحية'), included: true },
          { _key: 'pre-f-8', text: L('Enterprise API and integration support', 'دعم API المؤسسي والتكاملات'), included: true },
          { _key: 'pre-f-9', text: L('Advanced security controls and audit readiness', 'ضوابط أمان متقدمة وجهوزية للتدقيق'), included: true },
          { _key: 'pre-f-10', text: L('Predictive operations insights and optimization recommendations', 'رؤى تشغيل تنبؤية وتوصيات تحسين'), included: true },
          { _key: 'pre-f-11', text: L('Unlimited web pages, chat widgets, and AI agents', 'صفحات ويب غير محدودة ووحدات دردشة ووكلاء ذكاء اصطناعي'), included: true },
          { _key: 'pre-f-12', text: L('Priority support and implementation guidance', 'دعم أولوية وإرشاد في التنفيذ'), included: true },
          { _key: 'pre-r-1', text: L('System User: 250 EGP per user/month', 'مستخدم النظام: 250 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pre-r-2', text: L('Employee: 25 EGP per user/month', 'الموظف: 25 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pre-r-3', text: L('Driver: 150 EGP per user/month', 'السائق: 150 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pre-r-4', text: L('Driver with GPS: 350 EGP per user/month', 'السائق مع GPS: 350 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pre-r-5', text: L('Dependent: 300 EGP per user/month', 'التابع: 300 جنيه لكل مستخدم/شهر'), included: true },
          { _key: 'pre-r-6', text: L('White Labeling: 20,000 EGP per month', 'العلامة البيضاء: 20,000 جنيه شهريًا'), included: true },
        ],
        ctaText: L('Choose Premium', 'اختر Premium'),
        ctaHref: '/contact',
        highlighted: true,
      },
    ],
  },
  comparisonTable: {
    heading: L('Feature Comparison', 'مقارنة المزايا'),
    subtitle: L('Compare plan coverage for operational and governance needs.', 'قارن تغطية الباقات لاحتياجات التشغيل والحوكمة.'),
    tableHeaderFeature: L('Feature', 'الميزة'),
    tableHeaderStarter: L('Starter', 'Starter'),
    tableHeaderProfessional: L('Professional', 'Professional'),
    tableHeaderEnterprise: L('Enterprise', 'Premium'),
    features: [
      { _key: 'cmp-1', feature: L('Employee & rider management', 'إدارة الموظفين والركاب'), starter: false, professional: true, enterprise: true },
      { _key: 'cmp-2', feature: L('Dispatch board and trip scheduling', 'لوحة التشغيل وجدولة الرحلات'), starter: false, professional: true, enterprise: true },
      { _key: 'cmp-3', feature: L('SLA compliance tracking', 'تتبع الالتزام باتفاقية الخدمة'), starter: false, professional: false, enterprise: true },
      { _key: 'cmp-4', feature: L('White-labeled applications', 'تطبيقات بعلامة بيضاء'), starter: false, professional: false, enterprise: true },
      { _key: 'cmp-5', feature: L('Trip-level margin analytics', 'تحليلات هامش الربح على مستوى الرحلة'), starter: false, professional: false, enterprise: true },
      { _key: 'cmp-6', feature: L('Priority support', 'دعم أولوية'), starter: false, professional: false, enterprise: true },
    ],
  },
  cta: ctaSection(
    'Need a Plan Fit Assessment?',
    'تحتاج تقييمًا لاختيار الباقة المناسبة؟',
    'Share your user mix and operating model. We will map the most cost-effective setup.',
    'شاركنا مزيج المستخدمين ونموذج التشغيل لديكم، وسنحدد لكم التهيئة الأكثر كفاءة من حيث التكلفة.',
    'Talk to Sales',
    'تواصل مع المبيعات',
    '/contact',
    'Book a Demo',
    'احجز عرضًا تجريبيًا',
    '/contact',
  ),
}
